openapi: 3.0.3
info:
  title: API Sankhya
  description: >
    API de Integrações com Gateway Sankhya.


    Os endpoints aqui documentados estão todos baseados no EasyAPI, seguindo
    padrão Rest e documentação padrão OpenAPI/Swagger.


    Para utilizar todos os serviços, é necessário realizar o login conforme
    descrito na documentação.
  termsOfService: 'https://www.sankhya.com.br/'
  license:
    name: Licença Sankhya
    url: 'https://www.sankhya.com.br/'
  version: '1.0'
servers:
  - url: 'https://api.sankhya.com.br'
    description: Produção
  - url: 'https://api.sandbox.sankhya.com.br'
    description: Sandbox
security:
  - Bearer: []
tags:
  - name: Autenticação
    description: Fluxo de Autenticação para utilizar APIs Gateway da Sankhya
  - name: Cadastros Básicos
    description: Cadastros Básicos disponíveis no SankhyaOM
  - name: Clientes
    description: 'Cadastrar, atualizar e retornar clientes disponíveis no SankhyaOm'
  - name: Estoque
    description: Retorna estoque de produto existente no SankhyaOm
  - name: Financeiros Cadastros
    description: Breve descrição sobre o respectivo contexto
  - name: Financeiros Movimentos
    description: Breve descrição sobre o respectivo contexto
  - name: Fiscal
    description: Breve descrição sobre o respectivo contexto
  - name: HCM Cadastros
    description: Cadastros Básicos relacionados a Pessoal no SankhyaOm
  - name: HCM Funcionários
    description: Cadastros relacionados a Funcionários no SankhyaOm
  - name: HCM Integrações
    description: Endpoints destinados ao consumo das integrações HCM.
  - name: Logística
    description: >-
      Cadastros básicos relacionados a motorista, transportadora, ordens de
      carga, veículos, no Sankhya Om
  - name: Preços
    description: Breve descrição sobre o respectivo contexto
  - name: Produtos
    description: Cadastros Relacionados a Produtos
  - name: Vendas Pedidos
    description: Enviar Pedidos de Venda
  - name: Vendas CF-e/SAT
    description: Cupom Fiscal Eletrônico (CF-e/SAT)
  - name: Vendas NFC-e
    description: Nota Fiscal do Consumidor eletrônico (NFC-e)
  - name: Vendas Gestão de Caixa
    description: Gestão de Caixa (NFC-e e CF-e/SAT)
paths:
  /login:
    post:
      tags:
        - Autenticação
      summary: Autenticação com usuário e senha (fluxo legado)
      description: >
        Este serviço de login corresponde ao modelo de autenticação legado, que
        utiliza usuário, senha, appkey e token.


        Embora ainda esteja disponível para manter a compatibilidade com
        integrações existentes, ele foi substituído pelo novo fluxo OAuth 2.0,
        que oferece mais segurança e flexibilidade.


        **Recomendação**: Planeje a migração para o novo serviço `/authenticate`
        o quanto antes, garantindo que suas integrações estejam alinhadas ao
        padrão atual. O serviço `login` permanecerá disponível até
        **31/03/2026**, a partir desta data apenas o novo serviço estará
        disponível.


        Para utilizar o novo fluxo, basta criar um componente do tipo integração
        no Portal do Desenvolvedor. 


        [Clique aqui para ver como criar um novo componente de
        integração](https://developer.sankhya.com.br/docs/portal-do-desenvolvedor).


        **Fluxo recomendado:**

        1. Login (`/login`)

        2. Chamadas subsequentes usando o `bearerToken`

        3. Logout
        (`/gateway/v1/mge/service.sbr?serviceName=MobileLoginSP.logout`)


        - O `bearerToken` deve ser enviado no cabeçalho `Authorization` das
        chamadas subsequentes.

        - Sessão expira após 30 minutos de inatividade (configurável pelo
        parâmetro `INATSESSTIMEOUT`).

        - Recomenda-se sempre realizar **logout** ao final.


        Autentica o usuário no SankhyaOM utilizando **usuário, senha, appkey e
        token**.

        Retorna um `bearerToken` que deve ser utilizado em todas as requisições
        seguintes.
  /authenticate:
    post:
      tags:
        - Autenticação
      summary: Autenticação com OAuth 2.0 (Client Credentials)
      description: >
        Este serviço implementa o fluxo **OAuth 2.0 Client Credentials**, com
        uso adicional do cabeçalho `X-Token`. Ele substitui o modelo antigo
        baseado em **appkey + token** e oferece maior segurança e flexibilidade,
        permitindo autenticação em todo o ecossistema de softwares do Grupo
        Sankhya.


        [Clique aqui para ver como criar um novo componente de
        integração](https://developer.sankhya.com.br/docs/portal-do-desenvolvedor).


        Gera um access token JWT para autenticação em APIs do ecossistema
        Sankhya.

        É necessário enviar:

        - `client_id` e `client_secret` fornecidos na Área do Desenvolvedor

        - `X-Token` obtido na tela **Configurações Gateway** do Sankhya Om (ou
        de outros sistemas do grupo)
  /v1/vendas/cfe-sat:
    post:
      tags:
        - Vendas CF-e/SAT
      summary: Incluir Cupom Fiscal eletronico
      description: Inclui um Cupom Fiscal eletronico modelo 59 emitido em um PDV externo.
      operationId: addCfeSat
      security:
        - Bearer:
            - 'write:vendas/cfe-sat'
            - 'read:vendas/cfe-sat'
  /v1/vendas/cfe-sat/cancelar:
    post:
      tags:
        - Vendas CF-e/SAT
      summary: Cancela Cupom Fiscal eletronico
      description: Cancela um Cupom Fiscal eletronico modelo 59 emitido em um PDV externo.
      operationId: cancelaCfeSat
      security:
        - Bearer:
            - 'write:vendas/cfe-sat/cancelar'
            - 'read:vendas/cfe-sat/cancelar'
  /v1/vendas/cfe-sat/inutilizar:
    post:
      tags:
        - Vendas CF-e/SAT
      summary: Inutiliza Numeração de Cupom Fiscal eletronico
      description: >-
        Inutiliza Numeração de Cupom Fiscal eletronico modelo 59 emitido em um
        PDV externo.
      operationId: inutilizaCfeSat
      security:
        - Bearer:
            - 'write:vendas/cfe-sat/inutilizar'
            - 'read:vendas/cfe-sat/inutilizar'
  /v1/vendas/nfce:
    post:
      tags:
        - Vendas NFC-e
      summary: Incluir Nota Fiscal de Consumidor eletronico
      description: >-
        Inclui uma Nota Fiscal de Consumidor eletronico modelo 65 emitido em um
        PDV externo.
      operationId: addNfce
      security:
        - Bearer:
            - 'write:vendas/nfce'
            - 'read:vendas/nfce'
  /v1/vendas/nfce/autorizar:
    post:
      tags:
        - Vendas NFC-e
      summary: Autoriza Nota Fiscal de Consumidor eletronico que está em contigência
      description: >-
        Autoriza um Nota Fiscal de Consumidor eletronico modelo 59 emitido em um
        PDV externo que está armazenado no SankhyaOm. É importante ressaltar que
        a NFC-e deve ter sido previamente emitida em modo contingência
        (tipoEmissao = 9).
      operationId: autorizaCfeSat
      security:
        - Bearer:
            - 'write:vendas/cfe-sat'
            - 'read:vendas/cfe-sat'
  /v1/vendas/nfce/cancelar:
    post:
      tags:
        - Vendas NFC-e
      summary: Cancela Nota Fiscal de Consumidor eletronico
      description: >-
        Cancela uma Nota Fiscal de Consumidor eletronico modelo 65 emitido em um
        PDV externo.
      operationId: cancelaNfce
      security:
        - Bearer:
            - 'write:vendas/nfce/cancelar'
            - 'read:vendas/nfce/cancelar'
  /v1/vendas/nfce/inutilizar:
    post:
      tags:
        - Vendas NFC-e
      summary: Inutiliza Numeração de Nota Fiscal de Consumidor eletronico
      description: >-
        Inutiliza Numeração de Nota Fiscal de Consumidor eletronico modelo 65
        emitido em um PDV externo.
      operationId: inutilizaNfce
      security:
        - Bearer:
            - 'write:vendas/nfce/inutilizar'
            - 'read:vendas/nfce/inutilizar'
  /v1/caixa/abertura:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra a abertura do Caixa/PDV
      description: >-
        Este endpoint permite realizar a abertura de um Caixa/PDV no SankhyaOm.
        Para que o processo ocorra corretamente, o operador deve estar
        previamente vinculado ao cadastro do PDV no SankhyaOm. 


        É importante observar que o SankhyaOm não permite mais de um "Caixa
        Aberto" simultaneamente para o mesmo PDV, isso para garantir a
        integridade da operação.


        Ao abrir o Caixa/PDV, a API retornará o identificador codigoCaixa, que
        representa o "Caixa Aberto" para o período em questão. Esse codigoCaixa
        deve ser utilizado para realizar o fechamento do caixa e vincular todos
        os movimentos de venda ao respectivo "Caixa Aberto", garantindo a
        correta rastreabilidade das operações.
      operationId: addAbreCaixaPDV
      security:
        - Bearer:
            - 'write:caixa/abertura'
            - 'read:caixa/abertura'
  /v1/caixa/aberto:
    get:
      tags:
        - Vendas Gestão de Caixa
      summary: Busca o codigoCaixa aberto para o Caixa/PDV e Operador.
      description: >-
        Retorna o codigoCaixa que está aberto para o critério enviado para
        consulta.
      operationId: getCaixaAberto
      security:
        - Bearer:
            - 'write:caixa/abertura'
            - 'read:caixa/abertura'
  /v1/caixa/fechamento:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra o fechamento do Caixa/PDV
      description: >-
        Este serviço realiza o fechamento do Caixa/PDV que está aberto. Este
        processo permite enviar os valores transacionados no Caixa/PDV por "Tipo
        de Pagamento", isso irá apoiar no processo de Gestão de Caixa disponível
        no SankhyaOm.
      operationId: addFechaCaixaPDV
      security:
        - Bearer:
            - 'write:caixa/fechamento'
            - 'read:caixa/fechamento'
  /v1/caixa/sangria:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra sangria para um Caixa/PDV
      description: Registra sagria para um Caixa/PDV.
      operationId: addSangriaCaixaPDV
      security:
        - Bearer:
            - 'write:caixa/sangria'
            - 'read:caixa/sangria'
  /v1/caixa/suprimento:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra suprimento para um Caixa/PDV
      description: Registra suprimento para um Caixa/PDV.
      operationId: addSuprimentoCaixaPDV
      security:
        - Bearer:
            - 'write:caixa/suprimento'
            - 'read:caixa/suprimento'
  /v1/caixa/recebimento:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra recebimento para um Caixa/PDV
      description: Registra recebimento para um Caixa/PDV.
      operationId: addRecebimentoCaixaPDVinc
      security:
        - Bearer:
            - 'write:caixa/recebimento'
            - 'read:caixa/recebimento'
  /v1/caixa/recebimento/baixa:
    post:
      tags:
        - Vendas Gestão de Caixa
      summary: Registra recebimento para um Caixa/PDV
      description: Registra recebimento para um Caixa/PDV.
      operationId: addRecebimentoCaixaPDVbaixa
      security:
        - Bearer:
            - 'write:caixa/recebimento'
            - 'read:caixa/recebimento'
  '/v1/precos/produto/{codigoProduto}/tabela/{codigoTabela}':
    get:
      tags:
        - Preços
      summary: Obter preços vinculados a um produto e uma tabela de preço
      description: >-
        Este serviço retorna os preços do produto enviado no contexto e que
        estão associados à tabela de preços enviada no contexto. Pode haver mais
        de um preço, pois o produto pode ter volume alternativo, variação de
        preço por local de armazenamento e também preço variado por controle
        (ex.: sabor, cor, tamanho, etc.). Este serviço retorna até 50 registros
        por página.
      operationId: getPrecoProdutoTabela
      security:
        - Bearer:
            - 'write:/v1/precos/produto/tabela'
            - 'read:/v1/precos/produto/tabela'
  '/v1/precos/produto/{codigoProduto}':
    get:
      tags:
        - Preços
      summary: Obter preços vinculados a um produto independente da tabela de preço
      description: >-
        Este serviço retorna os preços do produto enviado no contexto, bem como
        as tabelas de preços nele relacionado. Vale ressaltar que cada produto x
        tabela de preços pode possuir mais de um preço, pois o produto pode ter
        volume alternativo, variação de preço por local de armazenamento e
        também preço variado por controle (ex.: sabor, cor, tamanho, etc.). Este
        serviço retorna até 50 registros por página.
      operationId: getPrecoProduto
      security:
        - Bearer:
            - 'write:/v1/precos/produto'
            - 'read:/v1/precos/produto'
  '/v1/precos/tabela/{codigoTabela}':
    get:
      tags:
        - Preços
      summary: Obter preços vinculados a um produto e uma tabela de preço
      description: >-
        Este serviço retorna os preços de todos os produtos vinculados à tabela
        de preços enviada no contexto. Vale ressaltar que cada produto x tabela
        de preços pode possuir mais de um preço, pois o produto pode ter volume
        alternativo, variação de preço por local de armazenamento e também preço
        variado por controle (ex.: sabor, cor, tamanho, etc.). Este serviço
        retorna até 50 registros por página.
      operationId: getPrecoTabela
      security:
        - Bearer:
            - 'write:/v1/precos/tabela'
            - 'read:/v1/precos/tabela'
  /v1/precos/contextualizado:
    post:
      tags:
        - Preços
      summary: Obter preços de produtos de forma contextualizada
      description: >-
        Este serviço retorna os preços dos produtos de forma contextualizada,
        levando em conta as condições específicas de uma negociação. O preço
        pode variar com base em diversos fatores, como forma de pagamento,
        localização do cliente, vendedor responsável pela negociação, entre
        outros. A consulta permite até 50 produtos por solicitação.
      operationId: getPrecoContexto
      security:
        - Bearer:
            - 'write:/v1/precos/contextualizado'
            - 'read:/v1/precos/contextualizado'
  /v1/funcionarios/admissao:
    post:
      deprecated: true
      summary: Criar uma nova requisição de admissão
      tags:
        - HCM Cadastros
      description: >
        Este endpoint permite o registro de uma nova requisição de admissão,
        incluindo informações detalhadas sobre o trabalhador, seu cargo,
        categoria, dados contratuais e cadastrais.
      security:
        - Bearer:
            - 'write:Requisição de admissão'
            - 'read:Requisição de admissão'
  '/v1/funcionarios/admissao/{codigoRequisicaoAdmissao}':
    get:
      deprecated: true
      summary: Buscar detalhes de uma requisição de admissão
      tags:
        - HCM Cadastros
      description: >-
        Este endpoint permite buscar os detalhes de uma requisição de admissão
        existente.
  /v2/funcionarios/admissao:
    post:
      summary: Criar uma nova requisição de admissão
      tags:
        - HCM Cadastros
      description: >-
        Este endpoint permite o registro de uma nova requisição de admissão,
        incluindo informações detalhadas sobre o trabalhador, seu cargo,
        categoria, dados contratuais e cadastrais. 

         Versão mínima do módulo pessoal: **5.26.0**
  '/v2/funcionarios/admissao/{codigoRequisicaoAdmissao}':
    get:
      summary: Buscar detalhes de uma requisição de admissão
      tags:
        - HCM Cadastros
      description: >-
        Este endpoint permite buscar os detalhes de uma requisição de admissão
        existente. 

         Versão mínima do módulo pessoal: **5.26.0**
  /v1/fiscal/servicos-tomados/nfse:
    post:
      tags:
        - Fiscal
      summary: Importar Nota Fiscal de Serviço
      description: >
        Disponível a partir da versão 4.32 do SankhyaOm, a API de Importação de
        Notas Fiscais de Serviços Tomados foi projetada para simplificar e
        automatizar o processo de importação de notas fiscais emitidas por
        fornecedores. Essa integração permite que empresas importem de forma
        eficiente e segura os dados fiscais diretamente para seus sistemas de
        gestão, eliminando a necessidade de inserção manual e reduzindo erros
        humanos.

        - Benefícios de utilizar a API estão na eficiência operacional, redução
        de erros, conformidade legal, integração flexivel e escalabilidade.

        - Para evitar a duplicidade na escrituração de documentos, o serviço
        utiliza uma chave única composta pelos seguintes elementos: CNPJ do
        Prestador, Número da Nota, Número do RPS, Série da Nota e data de
        emissão. Essa chave única garante que cada documento fiscal seja
        registrado apenas uma vez, prevenindo inconsistências e duplicações.
      security:
        - Bearer:
            - 'write:bairros'
            - 'read:bairros'
  /v1/vendas/pedidos:
    post:
      tags:
        - Vendas Pedidos
      summary: Incluir Pedido de Venda
      description: >
        Inclui um Pedido de Venda no Sankhya Om, SEMPRE A CONFIRMAR. Os
        financeiros que serão enviados não serão registrados como baixados, e
        sim pendentes. Obs.: a API não preve configurações de parceiro,
        alíquotas de impostos, etc, os mesmos já devem estar previamente
        configurados.

        - Versão mínima requirida do Sankhya Om para utilizar essa API: 4.34
      operationId: addPedido
      security:
        - Bearer:
            - 'write:vendas/pedidos'
            - 'read:vendas/pedidos'
  '/v1/vendas/pedidos/{codigoPedido}':
    put:
      tags:
        - Vendas Pedidos
      summary: Atualizar Pedido de Venda
      description: >
        A atualização de um Pedido de Venda já confirmado só é permitida se a
        TOP do pedido estiver configurada com a opção 'Permitir Alteração após
        Confirmar' ativada. Alem disto, na alteração de pedido, sempre enviar o
        itens e os financeiros.

        - Versão mínima requirida do Sankhya Om para utilizar essa API: 4.34
      operationId: putPedido
      security:
        - Bearer:
            - 'write:vendas/pedidos'
            - 'read:vendas/pedidos'
  '/v1/vendas/pedidos/{codigoPedido}/cancela':
    post:
      tags:
        - Vendas Pedidos
      summary: Cancela Pedido de Venda
      description: >
        Cancela um Pedido de Venda disponível do Sankhya Om. Obs.: Pedidos
        faturados não serão cancelados.

        - Versão mínima requirida do Sankhya Om para utilizar essa API: 4.34
      operationId: postCancelaPedido
      security:
        - Bearer:
            - 'write:vendas/pedidos'
            - 'read:vendas/pedidos'
  /v1/parceiros/clientes:
    get:
      tags:
        - Clientes
      summary: Retornar lista de clientes
      description: >
        Permite acessar a lista de clientes cadastrados no ERP. A resposta da
        API contém apenas os clientes ativos ou inativos que já foram
        cadastrados previamente no ERP.
      operationId: getCliente
      security:
        - Bearer:
            - 'write:clientes'
            - 'read:clientes'
    post:
      tags:
        - Clientes
      summary: Incluir cliente
      description: |
        Permite incluir um cliente no ERP.
      operationId: postCliente
      security:
        - Bearer:
            - 'write:clientes'
            - 'read:clientes'
  '/v1/parceiros/clientes/{codigoCliente}/contatos':
    post:
      tags:
        - Clientes
      summary: Incluir contatos para o cliente
      description: |
        Permite incluir um contato para um cliente já cadastrado.
      operationId: postContato
      security:
        - Bearer:
            - 'write:clientes'
            - 'read:clientes'
  '/v1/parceiros/clientes/{codigoCliente}':
    put:
      tags:
        - Clientes
      summary: Atualizar cliente
      description: |
        Permite atualizar um cliente previamente cadastrado.
                
      operationId: putCliente
      security:
        - Bearer:
            - 'write:clientes'
            - 'read:clientes'
  '/v1/parceiros/clientes/{codigoCliente}/contatos/{codigoContato}':
    put:
      tags:
        - Clientes
      summary: Atualizar contato do cliente
      description: |
        Permite atualizar um contato de um cliente previamente cadastrado
      operationId: putContatoCliente
      security:
        - Bearer:
            - 'write:clientes'
            - 'read:clientes'
  '/v1/estoque/produtos/{codigoProduto}':
    get:
      tags:
        - Estoque
      summary: Obter dados de estoque de um produto
      description: >

        - Este serviço verifica apenas o estoque registrado no ERP Sankhya, sem
        considerar o estoque do WMS.

        - Ele leva em conta apenas o estoque próprio da empresa, ignorando
        produtos armazenados por terceiros ou produtos de terceiros armazenados
        na empresa.

        - Além disso, a API só retorna informações sobre produtos que tiveram
        movimentação de estoque (entrada ou saída). Caso um produto tenha sido
        cadastrado, mas nunca tenha tido movimentação, ele não aparecerá na
        resposta da API, em vez de retornar um valor "estoque = zero".

        - Versão mínima requirida do Sankhya Om para utilizar essa API: 4.34
      operationId: getEstoquePorProduto
      security:
        - Bearer:
            - 'write:estoque'
            - 'read:estoque'
  /v1/estoque/produtos:
    get:
      tags:
        - Estoque
      summary: Obter dados de estoque de vários produtos
      description: >
        - Permite obter o estoque de vários produtos. - Este serviço verifica
        apenas os estoques registrado no ERP Sankhya, sem considerar os estoques
        do WMS.

        - Ele leva em conta apenas os estoques próprio da empresa, ignorando
        produtos armazenados por terceiros ou produtos de terceiros armazenados
        na empresa.

        - Além disso, a API só retorna informações sobre produtos que tiveram
        movimentação de estoque (entrada ou saída). Caso produtos tenham sido
        cadastrados, mas nunca tenham tido movimentação, eles não aparecerão na
        resposta da API, em vez de retornar um valor "estoque = zero".

        - Versão mínima requirida do Sankhya Om para utilizar essa API: 4.34
      operationId: getEstoqueProdutos
      security:
        - Bearer:
            - 'write:estoque'
            - 'read:estoque'
  /v1/fiscal/impostos/calculo:
    post:
      tags:
        - Fiscal
      summary: Calcular Impostos em Vendas
      description: >-
        Este endpoint calcula os impostos incidentes sobre uma operação de
        venda. Com base nos dados fornecidos, como empresa, cliente, produtos e
        despesas acessórias, a API retorna os valores calculados, incluindo base
        de cálculo, alíquotas e valores de impostos.


        É importante ressaltar que toda a parametrização tributária deve ser
        previamente configurada no SankhyaOm, pois o endpoint não realiza essa
        configuração, apenas aplica as regras já definidas no SankhyaOm.

         Serviço está disponível no SankhyaOm a partir da versão 4.31.
      security:
        - Bearer:
            - 'write:impostos'
            - 'read:impostos'
  /v1/naturezas:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Naturezas
      description: |
        Retorna a lista de Naturezas, com paginação, cadastradas no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/naturezas/{codigoNatureza}':
    get:
      tags:
        - Cadastros Básicos
      summary: Natureza Específica
      description: >-
        Retorna uma Natureza específica com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/centros-resultado:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Centros de Resultado
      description: >-
        Retorna a lista de Centro de Resultado, com paginação, cadastradas no
        SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/centros-resultado/{codigoCentroResultado}':
    get:
      tags:
        - Cadastros Básicos
      summary: Centro de Resultado Específico
      description: >-
        Retorna um Centro de Resultado específico com base no parâmetro enviado
        na requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/projetos:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Projetos
      description: |
        Retorna a lista de Projetos, com paginação, cadastradas no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/projetos/{codigoProjeto}':
    get:
      tags:
        - Cadastros Básicos
      summary: Projeto Específico
      description: >-
        Retorna um Projeto específico com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/tipos-operacao:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Tipos de Operação
      description: >
        Retorna a lista de Tipos de Operação, com paginação, cadastradas no
        SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/tipos-operacao/{codigoTipoOperacao}':
    get:
      tags:
        - Cadastros Básicos
      summary: Tipo de Operação Específico
      description: >-
        Retorna um Tipo de Operação específico com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/tipos-pagamento:
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Tipos de Pagamentos
      description: >-
        Retorna a lista de Tipos de Pagamento (Tipos de Títulos), com paginação,
        cadastradas no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/tipos-pagamento/{codigoTipoPagamento}':
    get:
      tags:
        - Financeiros Cadastros
      summary: Tipo de Pagamento específico
      description: >-
        Retorna um Tipo de Pagamento específico com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/moedas:
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Moedas
      description: |
        Retorna a lista de Moedas, com paginação, cadastradas no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/moedas/{codigoMoeda}':
    get:
      tags:
        - Financeiros Cadastros
      summary: Moeda Específica
      description: >-
        Retorna uma Moeda específica com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/moedas/{codigoMoeda}/cotacoes':
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Cotações de Moedas
      description: >
        Retorna uma lista de cotações da moeda envidad no contexto, com
        paginação, cadastradas no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/bandeiras-tef:
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Bandeiras TEF
      description: >-
        Retorna a lista de Bandeiras TEF, com paginação, cadastradas no
        SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/redes-tef:
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Redes (Adquirentes) TEF
      description: >-
        Retorna a lista de Redes (Adquirentes) TEF, com paginação, cadastradas
        no SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/contas-bancaria:
    get:
      tags:
        - Financeiros Cadastros
      summary: Lista de Contas Bancárias
      description: >-
        Retorna uma lista de Conta Bancária, com paginação, cadastradas no
        SankhyaOM.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/contas-bancaria/{codigoContaBancaria}':
    get:
      tags:
        - Financeiros Cadastros
      summary: Conta Bancária Específica
      description: >-
        Retorna uma Conta Bancária específica com base no parâmetro enviado na
        requisição.
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/receitas:
    get:
      tags:
        - Financeiros Movimentos
      summary: Obter receitas
      description: >-
        Endpoint `GET /v1/financeiros/receitas` - Fornece acesso aos dados
        financeiros de receitas cadastrados no SankhyaOM.
      operationId: getFinanceiros
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
    post:
      tags:
        - Financeiros Movimentos
      summary: Registra financeiro de receita
      description: Registra financeiro de receita
      operationId: addFinanceiroReceitaInclusao
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/receitas/{codigoFinanceiro}':
    put:
      tags:
        - Financeiros Movimentos
      summary: Atualizar Financeiro
      description: >-
        Endpoint `PUT /v1/financeiros/receitas/{codigoFinanceiro}` - Atualiza os
        dados financeiros de receitas cadastrados no SankhyaOM.
      operationId: addFinanceiroReceitaAtualizar
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/receitas/{codigoFinanceiro}/baixa':
    post:
      tags:
        - Financeiros Movimentos
      summary: Realiza baixa da Receitas
      description: Realiza baixa da Receitas
      operationId: addFinanceiroReceitasBaixa
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/financeiros/despesas:
    get:
      tags:
        - Financeiros Movimentos
      summary: Obter Despesas
      description: >-
        Endpoint `GET /v1/financeiros/despesas` - Fornece acesso aos dados
        financeiros de despesas lançados no SankhyaOM.
      operationId: getFinanceirosDespesas
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
    post:
      tags:
        - Financeiros Movimentos
      summary: Registra financeiro de despesa
      description: Registra financeiro de despesa
      operationId: addFinanceiroDespesaInclusao
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/despesas/{codigoFinanceiro}':
    put:
      tags:
        - Financeiros Movimentos
      summary: Atualizar Financeiro
      description: >-
        Endpoint `PUT /v1/financeiros/despesas/{codigoFinanceiro}` - Atualiza os
        dados financeiros de despesas cadastrados no SankhyaOM.
      operationId: addFinanceiroDespesaAtualizar
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  '/v1/financeiros/despesas/{codigoFinanceiro}/baixa':
    post:
      tags:
        - Financeiros Movimentos
      summary: Realiza baixa da Despesa
      description: Realiza baixa da Despesa
      operationId: addFinanceiroDespesaBaixa
      security:
        - Bearer:
            - 'write:financeiro'
            - 'read:financeiro'
  /v1/pessoal/cargos:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Cargos
      description: |-
        Retorna uma lista de Cargos, com paginação, cadastradas no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.48.0**
  '/v1/pessoal/cargos/{codigoCargo}':
    get:
      tags:
        - HCM Cadastros
      summary: Cargo específico
      description: >-
        Retorna um Cargo específico com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.48.0**
  /v1/pessoal/funcoes:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Funções
      description: |-
        Retorna uma lista de Funções, com paginação, cadastradas no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.48.0**
  '/v1/pessoal/funcoes/{codigoFuncao}':
    get:
      tags:
        - HCM Cadastros
      summary: Função específica
      description: >-
        Retorna uma Função específica com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.48.0**
  /v1/pessoal/departamentos:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Departamentos
      description: >-
        Retorna uma lista de Departamentos, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.48.0**
  '/v1/pessoal/departamentos/{codigoDepartamento}':
    get:
      tags:
        - HCM Cadastros
      summary: Departamento específico
      description: >-
        Retorna um Departamento específico com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.48.0**
  /v1/pessoal/locais-ponto:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Locais de Trabalho
      description: >-
        Retorna uma lista de Locais De Trabalho, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.48.0**
  '/v1/pessoal/locais-ponto/{codigoLocalPonto}':
    get:
      tags:
        - HCM Cadastros
      summary: Local De Trabalho específico
      description: >-
        Retorna um Local De Trabalho específico com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.48.0**
  /v1/pessoal/historicos-ocorrencia:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Histórico de ocorrências
      description: >-
        Retorna uma lista de Histórico de ocorrências, com paginação,
        cadastradas no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.50.0**
  '/v1/pessoal/historicos-ocorrencia/{codigoHistoricoOcorrencia}':
    get:
      tags:
        - HCM Cadastros
      summary: Histórico ocorrência espécífico
      description: >-
        Retorna um Histórico ocorrência específico com base no parâmetro enviado
        na requisição. 

         Versão mínima do módulo pessoal: **5.50.0**
  /v1/pessoal/ocorrencias:
    get:
      tags:
        - HCM Cadastros
      summary: Registro de todas as ocorrências
      description: |-
        Retorna todos os registros de ocorrência. 

         Versão mínima do módulo pessoal: **5.50.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/ocorrencias':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de Registros de Ocorrência de um determinado funcionário e empresa
      description: >-
        Retorna uma lista de Registros de Ocorrência, com paginação, cadastradas
        no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.50.0**
  /v1/pessoal/funcionarios:
    get:
      summary: Lista os funcionários modificados
      tags:
        - HCM Funcionários
      description: >-
        Retorna uma lista de funcionários, com paginação, cadastrados no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.51.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresa/{codigoEmpresa}':
    get:
      summary: Retorna os dados completos de um funcionário em uma empresa
      tags:
        - HCM Funcionários
      description: >-
        Retorna os dados de um funcionário em uma empresa com base nos
        parâmetros enviados na requisição. 

         Versão mínima do módulo pessoal: **5.51.0**
  /v1/pessoal/sindicatos:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Sindicatos
      description: >-
        Retorna uma lista de Sindicatos, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/sindicatos/{codigoSindicato}':
    get:
      tags:
        - HCM Cadastros
      summary: Sindicato específico
      description: >-
        Retorna um Sindicato específico com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/pessoal/faltas:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Faltas
      description: |-
        Retorna uma lista de Faltas, com paginação, cadastradas no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/faltas':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de registros de Faltas de um determinado funcionário e empresa.
      description: >-
        Retorna uma lista de Registros de Faltas, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/produtos/volumes:
    get:
      tags:
        - Produtos
      summary: Lista de Volumes de Produto
      description: 'Retorna uma lista de Volumes, com paginação, cadastrados no SankhyaOM.'
  '/v1/produtos/volumes/{codigoVolume}':
    get:
      tags:
        - Produtos
      summary: Volume específico
      description: >-
        Retorna um Volume específico com base no parâmetro enviado na
        requisição.
  /v1/pessoal/atrasos:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Atrasos
      description: |-
        Retorna uma lista de Atrasos, com paginação, cadastradas no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/atrasos':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de registros de Atrasos de um determinado funcionário e empresa.
      description: >-
        Retorna uma lista de Registros de Atrasos, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/pessoal/empresas:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Empresas
      description: >-
        Retorna uma lista de Empresas, com paginação, cadastradas no
        SankhyaOM.  

         Versão mínima do módulo pessoal: **5.54.0**
  '/v1/pessoal/empresas/{codigoEmpresa}':
    get:
      tags:
        - HCM Cadastros
      summary: Empresa específica
      description: >-
        Retorna uma empresa específica com base no parâmetro enviado na
        requisição.  

         Versão mínima do módulo pessoal: **5.54.0**
  /v1/pessoal/carga-horaria:
    get:
      tags:
        - HCM Cadastros
      summary: Registro de todas as cargas horárias
      description: |-
        Retorna todos os registros de cargas horárias. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/pessoal/carga-horaria-historica:
    get:
      tags:
        - HCM Cadastros
      summary: Registro de todas as cargas horárias históricas
      description: |-
        Retorna todos os registros de cargas horárias históricas. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/carga-horaria-historica':
    get:
      tags:
        - HCM Funcionários
      summary: >-
        Lista de Registros de carga horária histórica de um determinado
        funcionário e empresa
      description: >-
        Retorna uma lista de carga horária histórica, com paginação, cadastradas
        no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/estoque/locais:
    get:
      tags:
        - Estoque
      summary: Lista de Locais de Estoque
      description: >-
        Retorna uma lista de Locais de Estoque, com paginação, cadastradas no
        SankhyaOM.
  '/v1/estoque/locais/{codigoLocal}':
    get:
      tags:
        - Estoque
      summary: Local de Estoque específico
      description: >-
        Retorna um Local de Estoque específico com base no parâmetro enviado na
        requisição.
  /v1/parceiros/motoristas:
    get:
      tags:
        - Logística
      summary: Retornar lista de motoristas
      description: Permite acessar a lista de motoristas cadastrados no ERP.
      operationId: getMotoristas
      security:
        - Bearer: []
    post:
      tags:
        - Logística
      summary: Incluir motorista
      description: Permite incluir um motorista no ERP.
      operationId: postMotorista
      security:
        - Bearer: []
  '/v1/parceiros/motoristas/{codigoMotorista}':
    get:
      tags:
        - Logística
      summary: Consultar um motorista pelo código
      description: Retorna os dados de um motorista específico.
      operationId: getMotoristaById
      security:
        - Bearer: []
    put:
      tags:
        - Logística
      summary: Atualizar um motorista existente
      description: Permite atualizar os dados de um motorista específico pelo seu código.
      operationId: putMotorista
      security:
        - Bearer: []
  /v1/vendedores:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Vendedores
      description: >-
        Retorna uma lista de Vendedores, com paginação, cadastrados no
        SankhyaOM.
  '/v1/vendedores/{codigoVendedor}':
    get:
      tags:
        - Cadastros Básicos
      summary: Vendedor específico
      description: >-
        Retorna um Vendedor específico com base no parâmetro enviado na
        requisição.
  /v1/usuarios:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Usuários
      description: 'Retorna uma lista de Usuários, com paginação, cadastradas no SankhyaOM.'
  '/v1/usuarios/{codigoUsuario}':
    get:
      tags:
        - Cadastros Básicos
      summary: Usuário específico
      description: >-
        Retorna um Usuário específico com base no parâmetro enviado na
        requisição.
  /v1/logistica/ordens-carga:
    get:
      tags:
        - Logística
      summary: Retornar lista de Ordens de Carga
      description: >
        Permite acessar a lista de Ordens de Carga cadastradas no ERP, com a
        possibilidade de filtrar por empresa.
      operationId: getOrdensCarga
      security:
        - Bearer: []
    post:
      tags:
        - Logística
      summary: Incluir uma nova Ordem de Carga
      description: Permite incluir uma nova Ordem de Carga no ERP.
      operationId: postOrdemCarga
      security:
        - Bearer: []
  '/v1/logistica/empresas/{codigoEmpresa}/ordens-carga/{codigoOrdemCarga}':
    get:
      tags:
        - Logística
      summary: Consultar uma Ordem de Carga específica
      description: >-
        Retorna os dados de uma única Ordem de Carga a partir do seu código e do
        código da empresa.
      operationId: getOrdemCargaPorCodigo
      security:
        - Bearer: []
    put:
      tags:
        - Logística
      summary: Atualizar uma Ordem de Carga existente
      description: >
        Permite a atualização completa dos dados de uma Ordem de Carga  a partir
        do seu código de identificação e do código da empresa.
      operationId: putOrdemCarga
      security:
        - Bearer: []
  '/v1/logistica/empresas/{codigoEmpresa}/ordens-carga/{codigoOrdemCarga}/pedidos/{codigoPedido}':
    get:
      tags:
        - Logística
      summary: Consultar Pedidos da Ordem de Carga (Lista)
      description: >-
        Retorna a lista de pedidos atualmente associados a uma Ordem de Carga
        específica.
      operationId: getPedidosByOrdemCarga
    put:
      tags:
        - Logística
      summary: Adicionar Pedidos à Ordem de Carga (Lista)
      description: |-

        Adiciona um pedido a uma Ordem de Carga existente.



        **Regras para atualização de ordem de carga no pedido:**

        * A Ordem de Carga deve estar com a situação Aberta.

        * O pedido deve estar confirmado e não faturado totalmente.
      operationId: addPedidosToOrdemCarga
  '/v1/logistica/empresas/{codigoEmpresa}/ordens-carga/{codigoOrdemCarga}/pedidos/{codigoPedido}/delete':
    put:
      tags:
        - Logística
      summary: Remover Pedido Específico da Ordem de Carga
      description: >-

        Remove um único pedido de uma Ordem de Carga existente, identificado
        pelo `codigoPedido` no path.




        **Regras para atualização de ordem de carga no pedido:**


        * A Ordem de Carga deve estar com a situação Aberta.


        * O pedido deve estar confirmado e não faturado totalmente.
      operationId: removePedidoFromOrdemCarga
  /v1/produtos:
    get:
      tags:
        - Produtos
      summary: Lista de Produtos
      description: 'Retorna uma lista de Produtos, com paginação, cadastradas no SankhyaOM.'
  '/v1/produtos/{codigoProduto}':
    get:
      tags:
        - Produtos
      summary: Produto específico
      description: >-
        Retorna um Produto específico com base no parâmetro enviado na
        requisição.
  /v1/produtos/grupos:
    get:
      tags:
        - Produtos
      summary: Lista de Grupos de Produto
      description: >-
        Retorna uma lista de Grupos de Produto, com paginação, cadastradas no
        SankhyaOM.
  '/v1/produtos/grupos/{codigoGrupoProduto}':
    get:
      tags:
        - Produtos
      summary: Grupo de Produto específico
      description: >-
        Retorna um Grupo de Produto específico com base no parâmetro enviado na
        requisição.
  /v1/regioes:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Regiões
      description: 'Retorna uma lista de Regiões, com paginação, cadastradas no SankhyaOM.'
  '/v1/regioes/{codigoRegiao}':
    get:
      tags:
        - Cadastros Básicos
      summary: Região específica
      description: >-
        Retorna um Região específica com base no parâmetro enviado na
        requisição.
  /v1/cidades:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Cidades
      description: 'Retorna uma lista de Cidades, com paginação, cadastradas no SankhyaOM.'
  '/v1/cidades/{codigoCidade}':
    get:
      tags:
        - Cadastros Básicos
      summary: Cidade específica
      description: >-
        Retorna uma Cidade específica com base no parâmetro enviado na
        requisição.
  /v1/logradouros:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Logradouros
      description: >-
        Retorna uma lista de Logradouros, com paginação, cadastradas no
        SankhyaOM.
  '/v1/logradouros/{codigoLogradouro}':
    get:
      tags:
        - Cadastros Básicos
      summary: Logradouro específico
      description: >-
        Retorna um Logradouro específico com base no parâmetro enviado na
        requisição.
  /v1/parceiros/transportadoras:
    get:
      tags:
        - Logística
      summary: Retornar lista de transportadoras
      description: Permite acessar a lista de transportadoras cadastradas no ERP.
      operationId: getTransportadoras
      security:
        - Bearer: []
    post:
      tags:
        - Logística
      summary: Incluir transportadora
      description: Permite incluir uma transportadora no ERP.
      operationId: postTransportadora
      security:
        - Bearer: []
  '/v1/parceiros/transportadoras/{codigoTransportadora}':
    get:
      tags:
        - Logística
      summary: Consultar uma transportadora pelo código
      description: Retorna os dados de uma transportadora específica.
      operationId: getTransportadoraById
      security:
        - Bearer: []
    put:
      tags:
        - Logística
      summary: Atualizar uma transportadora existente
      description: >-
        Permite atualizar os dados de uma transportadora específica pelo seu
        código.
      operationId: putTransportadora
      security:
        - Bearer: []
  /v1/bairros:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Bairros
      description: 'Retorna uma lista de Bairros, com paginação, cadastradas no SankhyaOM.'
  '/v1/bairros/{codigoBairro}':
    get:
      tags:
        - Cadastros Básicos
      summary: Bairro específico
      description: >-
        Retorna um Bairro específico com base no parâmetro enviado na
        requisição.
  '/v1/produtos/{codigoProduto}/componentes':
    get:
      tags:
        - Produtos
      summary: Componentes de um respectivo Produto
      description: >-
        Retorna uma lista de Componentes que compõe um respectivo Produto,
        cadastradas no SankhyaOM.
  /v1/veiculos:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Veículos
      description: >-
        Retorna uma lista de Veículos ativos e inativos, com paginação,
        cadastradas no SankhyaOM.
  '/v1/veiculos/{codigoVeiculo}':
    get:
      tags:
        - Cadastros Básicos
      summary: Veículo específico
      description: >-
        Retorna um Veículo específico com base no parâmetro enviado na
        requisição.
  /v1/pessoal/identificacao-carga-horaria:
    get:
      tags:
        - HCM Cadastros
      summary: Lista todas as cargas horárias
      description: |-
        Retorna todos os registros de Identificação de Carga Horária. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/identificacao-carga-horaria/{codigoCargaHoraria}':
    get:
      tags:
        - HCM Cadastros
      summary: Identificação Carga Horária Específica
      description: >-
        Retorna um Cargo específico com base no parâmetro enviado na
        requisição. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/pessoal/tomadores:
    get:
      tags:
        - HCM Cadastros
      summary: Lista de Tomadores
      description: >-
        Retorna uma lista de Tomadores, com paginação, cadastradas no
        SankhyaOM.  

         Versão mínima do módulo pessoal: **5.55.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/tomadores':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de Registros de Tomadores de um determinado funcionário e empresa
      description: >-
        Retorna uma lista de Registros de Tomadores, com paginação, cadastradas
        no SankhyaOM.  

         Versão mínima do módulo pessoal: **5.55.0**
  '/v1/produtos/{codigoProduto}/volumes':
    get:
      tags:
        - Produtos
      summary: Volumes de um respectivo Produto
      description: >-
        Retorna uma lista de Volumes de um respectivo Produto, com paginação,
        cadastrados no SankhyaOM.
  '/v1/produtos/{codigoProduto}/alternativos':
    get:
      tags:
        - Produtos
      summary: Produtos Alternativos de um respectivo Produto
      description: >-
        Retorna uma lista de Produtos Alternativos de um respectivo Produto,
        cadastradas no SankhyaOM.
  /v1/empresas:
    get:
      tags:
        - Cadastros Básicos
      summary: Lista de Empresas
      description: 'Retorna uma lista de Empresas, com paginação, cadastradas no SankhyaOM.'
  '/v1/empresas/{codigoEmpresa}':
    get:
      tags:
        - Cadastros Básicos
      summary: Empresa específica
      description: >-
        Retorna uma empresa específica com base no parâmetro enviado na
        requisição.
  /v1/pessoal/ferias:
    get:
      tags:
        - HCM Cadastros
      summary: Registro de todas as férias
      description: |-
        Retorna todos os registros de férias. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/ferias':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de Registros de Férias de um determinado funcionário e empresa
      description: >-
        Retorna uma lista de Registros de Férias, com paginação, cadastradas no
        SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  /v1/pessoal/movimentos:
    get:
      tags:
        - HCM Cadastros
      summary: Registro de todos os movimentos
      description: |-
        Retorna todos os registros de movimentos. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresas/{codigoEmpresa}/movimentos':
    get:
      tags:
        - HCM Funcionários
      summary: Lista de Registros de Movimentos de um determinado funcionário e empresa
      description: >-
        Retorna uma lista de Registros de Movimentos, com paginação, cadastradas
        no SankhyaOM. 

         Versão mínima do módulo pessoal: **5.53.0**
  '/v1/pessoal/funcionarios/{codigoFuncionario}/empresa/{codigoEmpresa}/recibos-esocial':
    put:
      tags:
        - HCM Funcionários
      summary: Atualiza recibos eSocial SST do Funcionário
      description: >-
        Recebe, valida e persiste recibos e datas dos eventos SST do eSocial
        (S-2210, S-2220, S-2221, S-2240) para um funcionário/empresa.


        Observações:

        - Cada evento enviado deve conter os três campos: recibo, dataEvento e
        dataEnvio.

        - Apenas os eventos presentes no corpo serão processados.
         
  /v1/pessoal/inconsistencias:
    get:
      tags:
        - HCM Integrações
      summary: Consulta Inconsistências de integração
      description: >-
        Retorna a lista de Inconsistências identificadas nas rotinas de
        integração HCM.


        A resposta inclui o array `results` com as Inconsistências encontradas.
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: 'Insira o token com o prefixo ''Bearer: '' ex. "Bearer abcde12345".'
